### ISSUE TITLE
Add responsive email template

### ISSUE THREAD

**Issue by toolness** [18F/django-email-pal#1]
It would be nice if we used Lee Munroe's [Really Simple Responsive HTML Email Template](https://github.com/leemunroe/responsive-html-email-template) by default, while making it easy to override. This template is particularly useful as a default because it doesn't have any dependencies, yet it looks quite nice.

We don't need to worry about inlining our CSS since Gmail and most other mail clients now support `<style>` tags, though we might want to add optional support for it at some point, or something.

**Comment by cmc333333** [comment]
#8 and #10 should resolve
