### ISSUE TITLE
Consider using pytest-django

### ISSUE THREAD

**Issue by toolness** [18F/django-email-pal#18]
In #14 I added a `conftest.py` that manually configures django but it might be nicer to use [pytest-django](https://pytest-django.readthedocs.io/en/latest/) instead?  Not sure.

**Comment by tadhg-ohiggins** [comment]
From what I can tell, pytest-django expects a “real” Django project with a `manage.py` file, and while it might be possible to fake that, it seems to make more sense to keep using the `conftest.py` approach.

**Comment by toolness** [comment]
Oh ok, cool, thanks for investigating!
